- name: Install Nginx and deploy custom index.html
  hosts: webservers
  become: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy custom index.html
      copy:
        content: "hi jenkins ansible"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

